apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  selector:
    matchLabels:
      app: publisher
  replicas: 2
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: joembiye/publisher-arm64
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
spec:
  selector:
    app: nats
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 4222
  type: LoadBalancer