apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
spec:
  selector:
    matchLabels:
      app: subscriber
  replicas: 2
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
        - name: subscriber
          image: joembiye/subscriber-arm64
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: subscriber
spec:
  selector:
    app: nats
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 4222
  type: NodePort